/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminChangePasswordRouteImport } from './routes/admin.change-password'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AvtozapchastiIndexRouteImport } from './routes/avtozapchasti.index'
import { Route as AvtozapchastiSlugRouteImport } from './routes/avtozapchasti.$slug'
import { Route as CatalogProductIdRouteImport } from './routes/catalog.product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/admin/change-password',
  path: '/admin/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AvtozapchastiIndexRoute = AvtozapchastiIndexRouteImport.update({
  id: '/avtozapchasti/',
  path: '/avtozapchasti/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvtozapchastiSlugRoute = AvtozapchastiSlugRouteImport.update({
  id: '/avtozapchasti/$slug',
  path: '/avtozapchasti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogProductIdRoute = CatalogProductIdRouteImport.update({
  id: '/catalog/product/$id',
  path: '/catalog/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/avtozapchasti/$slug': typeof AvtozapchastiSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/avtozapchasti/': typeof AvtozapchastiIndexRoute
  '/catalog/product/$id': typeof CatalogProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/avtozapchasti/$slug': typeof AvtozapchastiSlugRoute
  '/admin': typeof AdminIndexRoute
  '/avtozapchasti': typeof AvtozapchastiIndexRoute
  '/catalog/product/$id': typeof CatalogProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/avtozapchasti/$slug': typeof AvtozapchastiSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/avtozapchasti/': typeof AvtozapchastiIndexRoute
  '/catalog/product/$id': typeof CatalogProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/change-password'
    | '/admin/login'
    | '/avtozapchasti/$slug'
    | '/admin/'
    | '/avtozapchasti/'
    | '/catalog/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/change-password'
    | '/admin/login'
    | '/avtozapchasti/$slug'
    | '/admin'
    | '/avtozapchasti'
    | '/catalog/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/change-password'
    | '/admin/login'
    | '/avtozapchasti/$slug'
    | '/admin/'
    | '/avtozapchasti/'
    | '/catalog/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AvtozapchastiSlugRoute: typeof AvtozapchastiSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AvtozapchastiIndexRoute: typeof AvtozapchastiIndexRoute
  CatalogProductIdRoute: typeof CatalogProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/admin/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avtozapchasti/': {
      id: '/avtozapchasti/'
      path: '/avtozapchasti'
      fullPath: '/avtozapchasti/'
      preLoaderRoute: typeof AvtozapchastiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avtozapchasti/$slug': {
      id: '/avtozapchasti/$slug'
      path: '/avtozapchasti/$slug'
      fullPath: '/avtozapchasti/$slug'
      preLoaderRoute: typeof AvtozapchastiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/product/$id': {
      id: '/catalog/product/$id'
      path: '/catalog/product/$id'
      fullPath: '/catalog/product/$id'
      preLoaderRoute: typeof CatalogProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AvtozapchastiSlugRoute: AvtozapchastiSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AvtozapchastiIndexRoute: AvtozapchastiIndexRoute,
  CatalogProductIdRoute: CatalogProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
